//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract()
        {
            this.TypeOfWork = new HashSet<TypeOfWork>();
        }
    
        public int ContractID { get; set; }
        public string ContractNumber { get; set; }
        public string ContractDate { get; set; }
        public string ContractObject { get; set; }
        public double ContractPrice { get; set; }
        public Nullable<int> ClientClientID { get; set; }
        public string ContractStatus { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfWork> TypeOfWork { get; set; }
    }
}
