//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int MaterialID { get; set; }
        public string MaterialName { get; set; }
        public double MaterialAmmount { get; set; }
        public double MaterialUnitPrice { get; set; }
        public string MaterialUnit { get; set; }
        public Nullable<int> WorkWorkID { get; set; }
    
        public virtual Work Work { get; set; }
    }
}
