//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataBaseLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Work()
        {
            this.Material = new HashSet<Material>();
        }
    
        public int WorkID { get; set; }
        public string WorkName { get; set; }
        public double WorkAmmount { get; set; }
        public string WorkUnit { get; set; }
        public double WorkUnitPrice { get; set; }
        public Nullable<int> TypeOfWorkTypeOfWorkID { get; set; }
    
        public virtual TypeOfWork TypeOfWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Material> Material { get; set; }
    }
}
